[tools]
go = "1.26.3"
kustomize = "5.8.1"
node = "26.1.0"
helm = "4.1.4"
rust = "1.95.0"
protoc = "34.1"
awscli = { version = "2.34.45", symlink_bins = "true" }
bazel = "8.5.0"
cloudflared = "2026.3.0"
dotnet = "10.0.203"
github-cli = "2.92.0"
minikube = "1.38.1"
aws-iam-authenticator = "0.7.15"
bun = "1.3.13"
argocd = "3.4.1"
fd = "10.4.2"
grpcurl = "1.9.3"
k9s = "0.50.16"
hyperfine = "1.20.0"
ruby = "4.0.3"
uv = "0.11.13"
terramate = "0.17.0"
hcl2json = "0.6.9"
atlas = "1.2.0"
terragrunt = "1.0.4"
ffmpeg = "8.1.1"
gcloud = "567.0.0"
k6 = "2.0.0"
krew = "0.5.0"
kubectl = "1.36.0"
mongosh = "2.8.3"
pnpm = "11.0.9"
teleport-community = "18.7.6"
terraform = "1.15.2"
yarn = "4.14.1"
redis = "8.6.3"
